### ISSUE TITLE
Binary/Source packages

### ISSUE THREAD

**Issue by aeantipov** [ALPSCore/ALPSCore#23]
Make deb / ppa / rpm / macports / homebrew.

**Comment by egull** [comment]
Release 0.3 AT LEAST for macports and debian

**Comment by egull** [comment]
was looking into dependencies on a specific variant in macports. This is needed for boost: if we have mpi, we need boost mpi, which is a variant of boost (+openmpi or +mpich). The quick answer is: macports does not support dependencies on variants, see here:
https://trac.macports.org/wiki/FAQ#dependonvariant
so we cannot depend on an mpi variant. The most we can do is check if boost was compiled with the mpi variant, and complain if it was not.

**Comment by aeantipov** [comment]
> The most we can do is check if boost was compiled with the mpi variant, and complain if it was not.
I agree. It should be the simplest to maintain.

**Comment by poboiko** [comment]
I wrote a simple ebuild for Gentoo GNU/Linux (sci-libs/alpscore-9999.ebuild), which I hope might be useful for somebody:
```
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=5

MY_PN="ALPSCore"

PYTHON_COMPAT=( python{2_5,2_6,2_7} )

inherit cmake-utils python-r1

if [[ ${PV} == "9999" ]]; then
	EGIT_REPO_URI="https://github.com/${MY_PN}/${MY_PN}.git"
	inherit git-r3
fi

DESCRIPTION="Algorithms and Libraries for Physics Simulations - core library"
HOMEPAGE="http://alpscore.org/"

LICENSE="GPL2"
SLOT="0"
KEYWORDS="~x86 ~amd64"
IUSE="python tutorials mpi doc tutorials test"

# hdf5[threads] needed for tebd
# szip, lpsolve

DEPEND=">=dev-libs/boost-1.47.0[mpi?,python?]
	>=sci-libs/hdf5-1.8.2 
	python? ( 
		${PYTHON_DEPS}
		dev-python/numpy
	)
	mpi? ( virtual/mpi )
	doc? ( app-doc/doxygen )"
RDEPEND="${DEPEND}"

src_configure() {
	mycmakeargs="
		$(cmake-utils_use python BuildPython)
		$(cmake-utils_use doc Documentation)
		$(cmake-utils_use tutorials BuildTutorials)
		$(cmake-utils_use test Testing)
		$(cmake-utils_use mpi ENABLE_MPI)
		"
	python_foreach_impl cmake-utils_src_configure
}

src_compile()
{
	python_foreach_impl cmake-utils_src_compile
}

src_install()
{
	python_foreach_impl cmake-utils_src_install
}
```

**Comment by aeantipov** [comment]
This looks nice. Added a new 'packaging' repo with the proposed ebuild. 
Check https://github.com/ALPSCore/packaging

**Comment by aeantipov** [comment]
2 @poboiko : can you add a simple readme with installation instructions? Check https://github.com/ALPSCore/packaging/tree/master/homebrew for an example

**Comment by poboiko** [comment]
Done. I created a pull request.

**Comment by galexv** [comment]
Merged. Thank you!

**Comment by egull** [comment]
I've added a first draft for a macports package. Right now it tries to overwrite python, and the dependencies are not resolved properly, but I'll fix that momentarily.

**Comment by egull** [comment]
OK, the ALPSCore package is submitted to macports. @galexv , you're the maintainer! Let me know if they complain about anything, I think they'll come to you, not me.

**Comment by egull** [comment]
@jpfleblanc, what is the unix system you use? We'll make a package for it...

**Comment by galexv** [comment]
> OK, the ALPSCore package is submitted to macports. @galexv , you're the maintainer! 
> Let me know if they complain about anything, I think they'll come to you, not me.

Ok. Deb package is the next thing to be made.

**Comment by egull** [comment]
First success: we've got ALPSCore in the version 0.4 into the official MacPorts repository. 'sudo port install ALPSCore' will now automatically fetch and install the package.

**Comment by aeantipov** [comment]
yay! Mind if I update the wiki page?

**Comment by egull** [comment]
go ahead.

**Comment by galexv** [comment]
It is possible to have Debian source built by Launchpad PPA (https://help.launchpad.net/Packaging/PPA) for AMD64 and x86.

**Comment by egull** [comment]
Closing. We will defer launchpad until the first person requests an ubuntu package. I've also updated the tutorial with a request for letting us know if people want other packages.
