### ISSUE TITLE
Some test fail with HDF5 1.10?

### ISSUE THREAD

**Issue by galexv** [ALPSCore/ALPSCore#290]
At least on Mac, a couple of tests (specifically, saving `long double` to HDF5; saving custom type to HDF5) fail with HDF5 1.10 (but not with HDF5 1.8).

**Comment by jgreitemann** [comment]
If it's any help, I can confirm that the following tests segfault when linking against HDF5-1.10.0-patch1:

```
The following tests FAILED:
	 15 - hdf5_complex (OTHER_FAULT)
	 16 - hdf5_bool (OTHER_FAULT)
	 17 - hdf5_copy (OTHER_FAULT)
	 18 - hdf5_exceptions (OTHER_FAULT)
	 19 - hdf5_family (OTHER_FAULT)
	 20 - hdf5_memory (OTHER_FAULT)
	 21 - hdf5_misc (OTHER_FAULT)
	 22 - hdf5_multiarchive (OTHER_FAULT)
	 23 - hdf5_pair (OTHER_FAULT)
	 24 - hdf5_real_complex (OTHER_FAULT)
	 25 - hdf5_real_complex_vec (OTHER_FAULT)
	 26 - hdf5_replace (OTHER_FAULT)
	 27 - hdf5_vecvecdbl (OTHER_FAULT)
	 28 - hdf5_vecveccplx (OTHER_FAULT)
	 29 - hdf5_io_types (OTHER_FAULT)
	 30 - hdf5_attributes (OTHER_FAULT)
	 32 - hdf5_large_array (OTHER_FAULT)
	 47 - save_load (OTHER_FAULT)
	 48 - save_load2 (OTHER_FAULT)
	 61 - custom_type (Failed)
	 73 - serialize (OTHER_FAULT)
	 75 - common_param_tests (OTHER_FAULT)
	 79 - sum_single (OTHER_FAULT)
	 80 - sum_mpi (Failed)
	 86 - mesh_test (OTHER_FAULT)
	 87 - one_index_gf_test (OTHER_FAULT)
	 89 - two_index_gf_test (OTHER_FAULT)
	 90 - three_index_gf_test (OTHER_FAULT)
	 91 - four_index_gf_test (OTHER_FAULT)
	 93 - itime_gf_test (OTHER_FAULT)
```

With the following stacktrace:
```
In /home/jgreitemann/opensource/ALPSCore/utilities/src/signal.cpp on 82 in segfault
    /home/jgreitemann/opensource/ALPSCore/build.tmp/utilities/libalps-utilities.so(_ZN4alps6signal8segfaultEi+0x45) [0x7f79901d6bd5]
    /lib64/libpthread.so.0(+0x115c0) [0x7f798e4cf5c0]
    /lib64/libc.so.6(strlen+0x26) [0x7f798d8dcfe6]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf56detail5error8callbackEjPK12H5E_error2_tPv+0x158) [0x7f7990594f28]
    /usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5-shared.so.100.0.1(H5E_walk+0x41c) [0x7f798ec99622]
    /usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5-shared.so.100.0.1(H5Ewalk2+0x22e) [0x7f798ec96bda]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf56detail5error6invokeB5cxx11Ei+0x290) [0x7f7990596460]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf56detail8resourceIXadL_Z8H5PcloseEEEC1Ei+0x146) [0x7f7990598706]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf56detail14archivecontext9constructEv+0xc6a) [0x7f799059a1ba]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf57archive9constructERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEm+0x302) [0x7f79904e1162]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf57archive4openERKN5boost10filesystem4pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xe2) [0x7f79904e1472]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf57archiveC1ERKN5boost10filesystem4pathENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x36) [0x7f79904e1956]
    hdf5/test/hdf5_family(_ZN36hdf5_TestingFamilyFunctionality_Test8TestBodyEv+0x11d) [0x4025fd]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x34) [0x7f798e714fb4]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing4Test3RunEv+0xba) [0x7f798e70d51a]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8TestInfo3RunEv+0x118) [0x7f798e70d668]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8TestCase3RunEv+0xb5) [0x7f798e70d745]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x227) [0x7f798e70d9f7]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x34) [0x7f798e715404]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8UnitTest3RunEv+0x40) [0x7f798e70dd00]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest_main.so(main+0x32) [0x7f798ffcc8e2]
    /lib64/libc.so.6(__libc_start_main+0xf1) [0x7f798d870401]
    hdf5/test/hdf5_family(_start+0x2a) [0x40235a]
Aborted (core dumped)
```

**Comment by jgukelberger** [comment]
Note that HDF5 1.10 introduced a bug that is triggered by repeated opening and closing of a dataset when the dataset was created using the same file descriptor. This is easily triggered by alps tests because the alps hdf5 module frequently opens and closes datasets in order to check their properties. See https://lists.phys.ethz.ch/pipermail/comp-phys-alps-users/2016/003145.html

However the bug should not result in a segfault, only an exception. Either the failure uncovers additional problems in the error handling or you are seeing a different bug.

We have reported the bug and a patch two months ago to the HDF Group. They reproduced and entered it into their (non-public) bug tracker, but we haven’t heard back since. For reference I’m attaching the bug report and patch.


> Begin forwarded message:
> 
> From: Jan Gukelberger <j.gukelberger@usherbrooke.ca>
> Subject: HDF5 bug in handling of non-chunked dataset layouts
> Date: December 5, 2016 at 23:02:49 GMT-5
> To: "help@hdfgroup.org" <help@hdfgroup.org>
> Cc: Michele Dolfi <dolfim@phys.ethz.ch>
> 
> VERSION: 
> 
> HDF5-1.10.0-patch1 and git development branch after commit 86f401d7407e3070cfa04359d4d04335addb83c7
> (regression from HDF5-1.8)
> 
> USER:
> 
> Jan Gukelberger <j.gukelberger@usherbrooke.ca> and Michele Dolfi <dolfim@phys.ethz.ch>
> 
> SYNOPSIS: 
> 
> Repeated opening and closing of a dataset that has just been created with H5D_COMPACT layout fails after a few H5Dopen/H5Dclose cycles.
> 
> MACHINE / OPERATING SYSTEM: 
> 
> Reproduced on macOS 10.10 and later and on GNU/Linux 2.6.32
> 
> COMPILER: 
> 
> Tested with Apple LLVM version 7.0.2 and GCC 4.8.2.
> 
> 
> DESCRIPTION: 
> 
> This bug triggered a test failure in the ALPS open source library (http://alps.comp-phys.org). In the following I attach a stripped-down example case that does not use ALPS. The code is written in C++ but uses only the C API of HDF5.
> 
> The attached code creates a new HDF5 file and writes a small dataset, namely a vector of 2 double numbers with H5D_COMPACT layout. Then, without closing the file in between, the dataset is opened and closed repeatedly using
> 
>         data_id = H5Dopen2(file_id_, “/mylist", H5P_DEFAULT);
>         H5Dclose(data_id);
> 
> This works without problems ten times, but the eleventh iteration fails in
> 
>         H5Dchunk.c line 635 in H5D__chunk_set_sizes(): chunk size must be < 4GB
> 
> See below for the full stack trace. The problem does not appear if the file is closed and reopened between dataset creation and the open/close loop. Calling H5Fflush() after dataset creation, on the other hand, does not help.
> 
> 
> STEPS TO REPRODUCE:
> 
> Save the attached files (writeflushread.cpp and Makefile) in a directory, set HDF5_ROOT in the Makefile or as environment variable and run 
>         make && ./writeflushread
> 
> The output on my system is reproduced below:
> 
> $ make
> c++  -I/Users/jan/opt/hdf5-devel_dbg/include -Wall -g -O0  -o writeflushread writeflushread.cpp -L/Users/jan/opt/hdf5-devel_dbg/lib  -lhdf5_hl -lhdf5 -lz -ldl -lm
> 
> $ ./writeflushread
> WRITE DONE
> H5Dopen2 #1
> H5Dopen2 #2
> H5Dopen2 #3
> H5Dopen2 #4
> H5Dopen2 #5
> H5Dopen2 #6
> H5Dopen2 #7
> H5Dopen2 #8
> H5Dopen2 #9
> H5Dopen2 #10
> H5Dopen2 #11
> HDF5-DIAG: Error detected in HDF5 (1.9.235) thread 0:
>   #000: H5D.c line 296 in H5Dopen2(): unable to open dataset
>     major: Dataset
>     minor: Can't open object
>   #001: H5Dint.c line 1375 in H5D__open_name(): can't open dataset
>     major: Dataset
>     minor: Unable to initialize object
>   #002: H5Dint.c line 1440 in H5D_open(): not found
>     major: Dataset
>     minor: Object not found
>   #003: H5Dint.c line 1649 in H5D__open_oid(): can't get layout/pline/efl info
>     major: Dataset
>     minor: Can't get value
>   #004: H5Dlayout.c line 661 in H5D__layout_oh_read(): unable to set chunk sizes
>     major: Dataset
>     minor: Bad value
>   #005: H5Dchunk.c line 635 in H5D__chunk_set_sizes(): chunk size must be < 4GB
>     major: Dataset
>     minor: Unable to initialize object
> libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: HDF5 error in resource::resource(hid_t)
> Abort trap: 6
> 
> 
> 
> 
> ANALYSIS:
> 
> After tracing the execution of the example code with a debugger my understanding of the problem is as follows. There appears to be a conjunction of two issues:
> 
> 1. In each H5Dopen() iteration, H5D__chunk_set_sizes() increments dataset->shared->layout.u.chunk.ndims and fills the corresponding value in dataset->shared->layout.u.chunk.dim with sizeof(double). This layout is written back by H5D__compact_flush() to the object header [or storage message? I don’t really understand the data structures. :)] during the H5Dclose() call, so each iteration will add a dimension until we end up with a chunk_size that does not fit into a 32-bit value any more. At this point H5D__chunk_set_sizes() fails. 
> 
> 2. During each H5Dopen() call, the dirty flag dataset->shared->layout.storage.u.compact.dirty is set to TRUE. This is the reason why the bogus layout is written back by H5D__compact_flush() in each H5Dclose() call again. In contrast, if the file was closed and reopened between creating the dataset and doing H5Dopen(), the dirty flag is false; in this case H5D__chunk_set_sizes() still increments layout.u.chunk.ndims, but the effects do not accumulate because the bogus layout is not flushed out, so each H5Dopen() call starts from a sane layout.
> 
> Regarding the first issue: As far as I can tell, H5D__layout_oh_read() should actually never call H5D__chunk_set_sizes() unless the dataset has H5D_CHUNKED layout. This is fixed in the attached patch.
> 
> Concerning the second issue: According to my debug traces H5D__compact_flush() always writes the complete layout including the current value of the dirty flag to the object header and then resets the dirty flag in dset->shared->layout (but not in the object header just written). So all subsequent H5Dopen() calls will read a layout marked as dirty right from the start. This seems curious, but without understanding the underlying data structures I cannot tell with certainty whether it is intended. If not (i.e. if the dirty flag only marks the need to flush the buffered layout to the object header), either H5D__compact_flush() should unset the dirty flag before the write or H5D__layout_oh_read() should to it after the read.
> 
> In case the above description misses some detail, the attached text file analysis.txt contains stack backtraces identifying the relevant locations that modify layout.u.chunk.ndims or layout.storage.u.compact.dirty in the buffer or object header.
> 
> 
> 
> PATCH:
> 
> The attached patch to H5D__layout_oh_read() fixes the first issue described in the analysis above by ensuring that H5D__chunk_set_sizes() is only called if the dataset has H5D_CHUNKED layout. Looking at git commit 86f401d7 this seems to be the original intent. With this patch the example code works as expected, i.e. all H5Dopen2() calls complete successfully.
> 
> 
> The second issue, that every H5Dopen2() call re-sets the flag layout.storage.u.compact.dirty to TRUE, is not touched by the patch. This behavior may or may not be a bug and should be judged by someone who understands the code. :-)
> 
> 
> 

>

**Comment by jgukelberger** [comment]
Patch to HDF5 1.10.0:

```
diff --git a/src/H5Dlayout.c b/src/H5Dlayout.c
index cb2eca2..415456e 100644
--- a/src/H5Dlayout.c
+++ b/src/H5Dlayout.c
@@ -657,7 +657,7 @@ H5D__layout_oh_read(H5D_t *dataset, hid_t dxpl_id, hid_t dapl_id, H5P_genplist_t
         HGOTO_ERROR(H5E_DATASET, H5E_CANTSET, FAIL, "can't set layout")
 
     /* Set chunk sizes */
-    if(H5D__chunk_set_sizes(dataset) < 0)
+    if(H5D_CHUNKED == dataset->shared->layout.type && H5D__chunk_set_sizes(dataset) < 0)
         HGOTO_ERROR(H5E_DATASET, H5E_BADVALUE, FAIL, "unable to set chunk sizes")
 
 done:
```

**Comment by galexv** [comment]
Thanks --- i will look at it.

**Comment by galexv** [comment]
I have compiled HDF5 1.10.0-patch1 library (source deb from Ubuntu Zesty), which does not contain patches from @jgukelberger,  on my machine (Ubuntu Trusty 14.04) and built ALPSCore with it. I see the same 2 tests fail as on Mac, but I do not see the segfaults. Jonas ( @jgreitemann), could you please provide more details how to reproduce the crashes? (E.g., the version of Linux, the version of compilers, the source of the new HDF5, the configured features of HDF5, ALPSCore building sequence...). Was it a clean build of ALPSCore?

**Comment by jgreitemann** [comment]
The system I tried this on is running Fedora 25. Compiler is GCC 6.3.1. Using the HDF5 1.8.17 from the Fedora repos, all the tests pass.

I got HDF5 1.10.0-patch1 straight from the HDF group's website and compiled it from source. Then, starting from a clean `build.tmp` dir, I did
```
$ cmake -DHDF5_DIR=/usr/local/HDF_Group/HDF5/1.10.0/share/cmake -DExtensiveTesting=1 ..
```
which picks up the correct locations for HDF5 includes and libs:
```
-- HDF5 includes: /usr/local/HDF_Group/HDF5/1.10.0/include
-- HDF5 libs: /usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5-shared.so.1.10.0;/usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5_cpp-shared.so.1.10.0
```
After `make`ing, I ran the tests as
```
$ LD_LIBRARY_PATH=/usr/local/HDF_Group/HDF5/1.10.0/lib make test
```
with the above results or individually, e.g.
```
$ LD_LIBRARY_PATH=/usr/local/HDF_Group/HDF5/1.10.0/lib hdf5/test/hdf5_complex 
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from hdf5_complex
[ RUN      ] hdf5_complex.TestingIoOfComplexVars
Abort by signal 11

In /home/jgreitemann/opensource/ALPSCore/utilities/src/signal.cpp on 82 in segfault
    /home/jgreitemann/opensource/ALPSCore/build.tmp/utilities/libalps-utilities.so(_ZN4alps6signal8segfaultEi+0x45) [0x7f257f651bd5]
    /lib64/libpthread.so.0(+0x115c0) [0x7f257d94a5c0]
    /lib64/libc.so.6(strlen+0x26) [0x7f257cd57fe6]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf56detail5error8callbackEjPK12H5E_error2_tPv+0x158) [0x7f257fa0ff28]
    /usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5-shared.so.100.0.1(H5E_walk+0x41c) [0x7f257e114622]
    /usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5-shared.so.100.0.1(H5Ewalk2+0x22e) [0x7f257e111bda]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf56detail5error6invokeB5cxx11Ei+0x290) [0x7f257fa11460]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf56detail14archivecontext9constructEv+0x2a67) [0x7f257fa16fb7]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf57archive9constructERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEm+0x302) [0x7f257f95c162]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf57archive4openERKN5boost10filesystem4pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xe2) [0x7f257f95c472]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so(_ZN4alps4hdf57archiveC1ERKN5boost10filesystem4pathENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x36) [0x7f257f95c956]
    hdf5/test/hdf5_complex(_ZN40hdf5_complex_TestingIoOfComplexVars_Test8TestBodyEv+0x10c) [0x40434c]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x34) [0x7f257db8ffb4]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing4Test3RunEv+0xba) [0x7f257db8851a]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8TestInfo3RunEv+0x118) [0x7f257db88668]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8TestCase3RunEv+0xb5) [0x7f257db88745]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x227) [0x7f257db889f7]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x34) [0x7f257db90404]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so(_ZN7testing8UnitTest3RunEv+0x40) [0x7f257db88d00]
    /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest_main.so(main+0x32) [0x7f257f4478e2]
    /lib64/libc.so.6(__libc_start_main+0xf1) [0x7f257cceb401]
    hdf5/test/hdf5_complex(_start+0x2a) [0x4040ba]
Aborted (core dumped)
```

Linker output:
```
$ LD_LIBRARY_PATH=/usr/local/HDF_Group/HDF5/1.10.0/lib ldd hdf5/test/hdf5_complex 
	linux-vdso.so.1 (0x00007ffc077f7000)
	libalps-hdf5.so => /home/jgreitemann/opensource/ALPSCore/build.tmp/hdf5/libalps-hdf5.so (0x00007f9e66e30000)
	libalps-utilities.so => /home/jgreitemann/opensource/ALPSCore/build.tmp/utilities/libalps-utilities.so (0x00007f9e66c22000)
	libgtest_main.so => /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest_main.so (0x00007f9e66a20000)
	libboost_chrono.so.1.60.0 => /lib64/libboost_chrono.so.1.60.0 (0x00007f9e667ed000)
	libmpi_cxx.so.1 => /usr/lib64/openmpi/lib/libmpi_cxx.so.1 (0x00007f9e665d0000)
	libmpi.so.12 => /usr/lib64/openmpi/lib/libmpi.so.12 (0x00007f9e662df000)
	libboost_filesystem.so.1.60.0 => /lib64/libboost_filesystem.so.1.60.0 (0x00007f9e660c9000)
	libboost_system.so.1.60.0 => /lib64/libboost_system.so.1.60.0 (0x00007f9e65ec5000)
	libboost_program_options.so.1.60.0 => /lib64/libboost_program_options.so.1.60.0 (0x00007f9e65c51000)
	libhdf5-shared.so.100.0.1 => /usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5-shared.so.100.0.1 (0x00007f9e655b8000)
	libhdf5_cpp-shared.so.100.0.1 => /usr/local/HDF_Group/HDF5/1.10.0/lib/libhdf5_cpp-shared.so.100.0.1 (0x00007f9e6534a000)
	libgtest.so => /home/jgreitemann/opensource/ALPSCore/build.tmp/gtest/libgtest.so (0x00007f9e65100000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9e64ee2000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9e64b5a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9e64851000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9e6463a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9e64272000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f9e6406a000)
	libopen-rte.so.12 => /usr/lib64/openmpi/lib/libopen-rte.so.12 (0x00007f9e63de5000)
	libopen-pal.so.13 => /usr/lib64/openmpi/lib/libopen-pal.so.13 (0x00007f9e63b48000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9e63944000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f9e63741000)
	libhwloc.so.5 => /lib64/libhwloc.so.5 (0x00007f9e63507000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a7a0f46000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f9e632fc000)
	libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f9e630f2000)
```

I was careful not to the get both HDF5 versions messed up but it seems to link against the correct one. Is there something obviously wrong with that approach? If not and you still can't reproduce, I can dig in further tomorrow. Maybe compile with debug symbols and step through to see where things go south.

**Comment by galexv** [comment]
@jgreitemann: Thank you for the step-by-step description, i will try to reproduce. The sequence seems reasonable, the only differences i see right away are a newer compiler (mine is 4.8.4) and Debian/Ubuntu patches (if any) on top of the original HDF5 source. Can it be something to do with changed ABI between gcc 4.8 and 6.x?

@jgukelberger: Applying the patch eliminated the test failures! (Thanks!)

**Comment by jgreitemann** [comment]
I installed gcc 4.9.4 and recompiled hdf5 1.10.0-patch1 with it. I also had to install boost (1.56) and openmpi (2.0.2) from source using gcc 4.9.4 because I was getting linker errors from the system versions. Indeed, the problem is gone now. Only the two tests you mentioned initially still fail, as one would expect.

So I guess this is an entirely separate issue. You should be able to reproduce by using gcc 6.x. As for the cause of the segfaults, I'm not convinced the ABI change would explain the problem. I would expect to see linker errors in that case. Both ALPSCore and HDF5 have been compiled with the same compiler, so why would the ABI be an issue? One significant difference between gcc 6.x and older versions is that gcc 6.x uses C++11 by default.

**Comment by galexv** [comment]
@jgreitemann: I am still not able to reproduce the segmentation fault on Ubuntu. Installed gcc-6 from PPA, compiled boost and (patched) HDF5, compiled ALPSCore (with MPI support OFF). All tests pass.

I am thinking of trying it on Fedora 25, if i will be able get an access to a machine (real or virtual).

**Comment by jgreitemann** [comment]
I'm certainly confused now. I tried to reproduce the problem myself on an Ubuntu system without any luck and then took to another Fedora 25 machine where I couldn't reproduce either. Thus, the issue is probably on my end. I'm slightly puzzled but will investigate further. In the meantime, I suggest you don't waste your time on it.

**Comment by galexv** [comment]
I think, for now we can [request](https://github.com/ALPSCore/ALPSCore/wiki/Installation#prerequisites) that users should use HDF5 1.8.x and wait till the bug is fixed in upstream HDF5.

**Comment by egull** [comment]
we still have this failure on hdf5 1.10.1, for the accumulators/test/custom_type and accumulators/test/save_load2

**Comment by galexv** [comment]
Another argument in favor of using HDF5 1.8 for now: https://lists.hdfgroup.org/pipermail/hdf-forum_lists.hdfgroup.org/2016-May/009481.html

In essence, HDF5 may fail to write to an HDF5 file on Lustre if Lustre locking mechanism is disabled by system administrator.

With 10.1 there came a [possible workaround](https://support.hdfgroup.org/ftp/HDF5/releases/ReleaseFiles/hdf5-1.10.1-RELEASE.txt): 

> The file locking calls used in HDF5 1.10.0 (including patch1)
>       will fail when the underlying file system does not support file
>       locking or where locks have been disabled. To disable all file
>       locking operations, an environment variable named
>       HDF5_USE_FILE_LOCKING can be set to the five-character string
>       'FALSE'. This does not fundamentally change HDF5 library
>       operation (aside from initial file open/create, SWMR is lock-free),
>       but users will have to be more careful about opening files
>       to avoid problematic access patterns (i.e.: multiple writers)
>       that the file locking was designed to prevent.

**Comment by galexv** [comment]
As we move away from the current accumulator library, this issue is not that relevant: it apparently pops up only with HDF5 1.10+ _and_ `long double` _or_ `custom_type`. None of those are actually used, Closing this for now.
Cross reference: issue #356
